export const TOGGLEFLAG = 'TOGGLEFLAG';
export const CHECKFORMINE = 'CHECKFORMINE';
export const RESETBOARD = 'RESETBOARD';
export const INCREASEBOARDSIZE = 'INCREASEBOARDSIZE';
export const DECREASEBOARDSIZE = 'DECREASEBOARDSIZE';
export const REVEALALL = 'REVEALALL';
